### ISSUE TITLE
Test for Ability Score Generators returning values above 18

### ISSUE THREAD

**Issue by fluffymuffin27** [fluffymuffin27/take10#2]
Currently we test for scores less than 0, but not for scores higher than 18, as noted on the [wiki planning document](https://github.com/fluffymuffin27/take10/wiki/Ability-Scores).

**Comment by IMPrager** [comment]
Keep in mind that Point Buy changes things up a bit:
- Rather than testing for scores less than 0, you need to prevent users from lowering scores below 7.

Users still can't increase scores above 18 as far as I know.

**Comment by hamiltonium** [comment]
I've altered the test to raise an error when dexterity is greater than 18.  For some reason, it looks like the coverage dropped a bit when I added that line of code.

**Comment by fluffymuffin27** [comment]
Coverage may have dropped because it might still consider whether the test files themselves are 'covered'. Not unusual.

Fixed by #4
